package vista;

import clases.modelo.productoBD;
import clases.producto;
import clases.proveedor;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


/**
 *
 * @author ASUS
 */
public class Producto extends javax.swing.JPanel {

    /**
     * Creates new form Proveedores
     */
    public Producto() {
        initComponents();
        cargarProveedores();
        configurarEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelRegistroP = new javax.swing.JPanel();
        TextNombre = new javax.swing.JTextField();
        TextPrecio = new javax.swing.JTextField();
        TextCantidad = new javax.swing.JTextField();
        TextCategoria = new javax.swing.JTextField();
        jComboProveedor = new javax.swing.JComboBox<>();
        jComboEstado = new javax.swing.JComboBox<>(new String[] { "Activo", "Inactivo", "Discontinuado" });
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        NombreP = new javax.swing.JLabel();
        PrecioP = new javax.swing.JLabel();
        ProveedorP = new javax.swing.JLabel();
        CategoriaP = new javax.swing.JLabel();
        EstadoP = new javax.swing.JLabel();
        CantidadP = new javax.swing.JLabel();
        TextID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelListaP = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(650, 420));

        jPanelRegistroP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNombreActionPerformed(evt);
            }
        });
        jPanelRegistroP.add(TextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 110, -1));

        TextPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrecioActionPerformed(evt);
            }
        });
        jPanelRegistroP.add(TextPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 110, -1));
        jPanelRegistroP.add(TextCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 110, -1));

        TextCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCategoriaActionPerformed(evt);
            }
        });
        jPanelRegistroP.add(TextCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 110, -1));

        jComboProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboProveedorActionPerformed(evt);
            }
        });
        jPanelRegistroP.add(jComboProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 110, -1));
        jPanelRegistroP.add(jComboEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 110, -1));

        jToggleButton1.setText("Agregar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanelRegistroP.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 110, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Registro de productos");
        jPanelRegistroP.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        NombreP.setText("Nombre del producto:");
        jPanelRegistroP.add(NombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        PrecioP.setText("Precio del producto:");
        jPanelRegistroP.add(PrecioP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        ProveedorP.setText("Proveedor del producto:");
        jPanelRegistroP.add(ProveedorP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        CategoriaP.setText("Categoria del producto:");
        jPanelRegistroP.add(CategoriaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 20));

        EstadoP.setText("Estado del producto:");
        jPanelRegistroP.add(EstadoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        CantidadP.setText("Cantidad del producto:");
        jPanelRegistroP.add(CantidadP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        TextID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIDActionPerformed(evt);
            }
        });
        jPanelRegistroP.add(TextID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 110, -1));

        jLabel2.setText("ID del producto:");
        jPanelRegistroP.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 120, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ImgProductos.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanelRegistroP.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 300, 300));

        jTabbedPane1.addTab("Registro", jPanelRegistroP);

        jPanelListaP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {"ID", "Nombre", "Precio", "Cantidad", "Categoría", "Estado", "Proveedor"}
        )
    );
    jScrollPane1.setViewportView(jTable1);

    jPanelListaP.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 440, 310));

    jTabbedPane1.addTab("Lista", jPanelListaP);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jTabbedPane1)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
    );
    }// </editor-fold>//GEN-END:initComponents

    private void TextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNombreActionPerformed

    private void jComboProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboProveedorActionPerformed

    private void TextCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCategoriaActionPerformed

    private void TextPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrecioActionPerformed

    private void TextIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIDActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // Verificar que todos los campos estén llenos
    if (TextID.getText().isEmpty() || TextNombre.getText().isEmpty() || TextPrecio.getText().isEmpty() || 
        TextCantidad.getText().isEmpty() || TextCategoria.getText().isEmpty() || 
        jComboProveedor.getSelectedItem() == null || jComboEstado.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
        return; // Salir del método si hay campos vacíos
    }

    try {
        // Crear una instancia de la clase producto
        int id = Integer.parseInt(TextID.getText());
        String nombre = TextNombre.getText();
        double precio = Double.parseDouble(TextPrecio.getText());
        int cantidad = Integer.parseInt(TextCantidad.getText());
        String categoria = TextCategoria.getText();
        String estado = jComboEstado.getSelectedItem().toString();
        // Asumiendo que tienes un proveedor preseleccionado desde un JComboBox
        proveedor proveedorSeleccionado = (proveedor) jComboProveedor.getSelectedItem();
        // Verificar que el proveedor seleccionado no sea null
        if (proveedorSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un proveedor.");
            return; // Salir si no se ha seleccionado proveedor
        }
        // Crear un producto con los datos
        producto nuevoProducto = new producto(id, nombre, precio, cantidad, proveedorSeleccionado, categoria, estado);
        // Llamar al método para agregar el producto a la base de datos
        productoBD productoBD = new productoBD();
        boolean exito = productoBD.agregarProducto(nuevoProducto);
        if (exito) {
            JOptionPane.showMessageDialog(this, "Producto agregado correctamente.");
            limpiarCampos(); // Limpia los campos después de insertar
            cargarProductosEnTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Error al agregar el producto.");
        }
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Error en los datos numéricos: " + e.getMessage());
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void configurarEventos() {
    jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
        public void stateChanged(javax.swing.event.ChangeEvent evt) {
            if (jTabbedPane1.getSelectedIndex() == 1) { // Índice 1 corresponde a la pestaña "Lista"
                cargarProductosEnTabla(); // Llamar al método que carga los datos en la tabla
            }
        }
    });
    }
    private void limpiarCampos() {
    TextID.setText("");
    TextNombre.setText("");
    TextPrecio.setText("");
    TextCantidad.setText("");
    TextCategoria.setText("");
    jComboEstado.setSelectedIndex(0); // Selecciona el primer elemento del ComboBox
    jComboProveedor.setSelectedIndex(0); // Selecciona el primer elemento del ComboBox
    }
    
    private void cargarProveedores() {
    productoBD productoBD = new productoBD();
    List<proveedor> proveedores = productoBD.listarProveedores();

    DefaultComboBoxModel<proveedor> modelo = new DefaultComboBoxModel<>();
    for (proveedor p : proveedores) {
        modelo.addElement(p); // Agrega el objeto proveedor
    }
    jComboProveedor.setModel(modelo);

    if (modelo.getSize() == 0) {
        JOptionPane.showMessageDialog(this, "No hay proveedores disponibles.");
    }
    }
    
    private void cargarProductosEnTabla() {
    // Crear una instancia de productoBD para obtener los productos
    productoBD productoBD = new productoBD();
    List<producto> producto = productoBD.listarProductos(); // Obtener productos desde la base de datos

    // Crear el modelo de la tabla si no lo tienes definido
    String[] columnNames = {"ID", "Nombre", "Precio", "Cantidad", "Categoría", "Estado", "Proveedor"};
    javax.swing.table.DefaultTableModel modeloTabla = new javax.swing.table.DefaultTableModel(columnNames, 0);

    // Agregar los productos al modelo de la tabla
    for (producto p : producto) {
        Object[] fila = {
            p.getId(),
            p.getNombre(),
            p.getPrecio(),
            p.getCantidad(),
            p.getCategoria(),
            p.getEstado(),
            p.getProveedor().getNombre() // Asegúrate de que `getNombre()` esté implementado en tu clase `proveedor`
        };
        modeloTabla.addRow(fila);
    }

    // Asignar el modelo a la tabla
    jTable1.setModel(modeloTabla);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CantidadP;
    private javax.swing.JLabel CategoriaP;
    private javax.swing.JLabel EstadoP;
    private javax.swing.JLabel NombreP;
    private javax.swing.JLabel PrecioP;
    private javax.swing.JLabel ProveedorP;
    private javax.swing.JTextField TextCantidad;
    private javax.swing.JTextField TextCategoria;
    private javax.swing.JTextField TextID;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JTextField TextPrecio;
    private javax.swing.JComboBox<String> jComboEstado;
    private javax.swing.JComboBox<proveedor> jComboProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanelListaP;
    private javax.swing.JPanel jPanelRegistroP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}